### ISSUE TITLE
批处理hunter的问题

### ISSUE THREAD

**Issue by kirilenkoo** [stdnull/StudyNotes#1]
private void batch(BitmapHunter hunter) {
    if (hunter.isCancelled()) {
      return;
    }
    batch.add(hunter);//添加到集合中
    if (!handler.hasMessages(HUNTER_DELAY_NEXT_BATCH)) {
      handler.sendEmptyMessageDelayed(HUNTER_DELAY_NEXT_BATCH, BATCH_DELAY);
    }
  }
请教一下，你在自问自答的批处理问题是不是说的这个方法，没太看懂这里跟合并actions有什么关系？

**Comment by getletCodes** [comment]
是指的这个方法.合并Action指的是重复的Action会对应一个BitmapHunter，实质上就只发送了一次请求，虽然回调会被掉多次。不过这个合并实在Action请求之前做的。
